### ISSUE TITLE
camera parameters

### ISSUE THREAD

**Issue by izzat1** [yanconglin/VanishingPoint_HoughTransform_GaussianSphere#3]
Thanks for posting your excellent code. I am interested in testing on my camera which is 2 M camera with focal length ~1200 and unequal principle point. How do I specify the focal length in the code? Do I need to create new parameter files with the new focal length?

**Comment by yanconglin** [comment]
to test a new image: use the demo (model trained on NYU, which assumes unit focal length and centered principle point).  no need to re-calculate the parameter files.  All predicted VPs will be on the image plane. 

If you want to train a new model on a new dataset with customized cameras: please re-compute the parameter files from scratch. All predicted VPs will be in the camera space. This is particularly useful in the Manhattan setting.

**Comment by izzat1** [comment]
Thanks for your input. closing
