### ISSUE TITLE
Image Size Error When Using ScanNet weights and config

### ISSUE THREAD

**Issue by iahmedmaher** [yanconglin/VanishingPoint_HoughTransform_GaussianSphere#6]
Hello,

First, thanks for open-sourcing the code!

Second, when I tried using the ScanNet weights and config on the sample image inside the repo or even on a ScanNet image, I get this error

`RuntimeError: height_ == height && width_== width INTERNAL ASSERT FAILED at "VanishingPoint_HoughTransform_GaussianSphere/vpd/models/ht/cpp_im2ht/ht_cuda.cu":38, please report a bug to PyTorch.  image shape and given shape params do not match: (%d x %d vs %d x %d).240320256256`

This doesn't happen when I use the NYU weights and config. 

Upon tracing the feature maps' tensor shapes, I found that resizing the input image to 512x512 instead of the coded 480x640 fixed this issue and produced qualitatively valid vanishing points (at least the horizontal ones). 

is this a valid fix or does it lead to subpar performance?

**Comment by yanconglin** [comment]
the mapping from pixels to the sphere depends on the image size. That is why you need to resize or recalculate the mapping.  So in this case (test scannet-pretrained model on the sample image (from YUD, 480x640), resizing is necessary. Undo the resizing before you do a quantitative evaluation.  The mismatch of image size and mapping size is indeed a drawback of this solution.

**Comment by iahmedmaher** [comment]
@yanconglin Thanks for your reply, but I want to double-check something. By "Undo the resizing before you do a quantitative evaluation", you mean supplying the original image's width and height to the "to_pixels" function if I am going to use the xs and ys or you are talking about something else?

**Comment by yanconglin** [comment]
say you get vps from a resized image of 480x640, then the parameters in the to_pixels function should also be 480 and 640. What I meant in the previous reply is the numerical evaluation, where it would be fair to rescale the predicted vps back to orignal size and then do the evaluation in the camera space. So if you are not doing the numerical evaluation, pls ignore.

**Comment by iahmedmaher** [comment]
Got it. Thanks a lot for your time!
